# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Maxim Grankin
title: Java developer
email: maximgran@gmail.com
phone: +7(962)401-15-60

additional_links:
  - title: "Telegram"
    icon: "fa-telegram"
    url: "https://t.me/VeriuMaxon"
  - title: "Vk"
    icon: "fa-vk"
    url: "https://vk.com/makcoooh"

# Social links
#twitter_username: facespics
github_username:  maxim092001
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Maxim and I'm a backend java developer. As well as creating RESTful services I also have experience
  making fintech software.
  I have worked at a number of startups and companies.

  I am most skilled in: <mark>Java</mark>, <mark>Spring boot</mark> and <mark>Algorithms and data structures</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Crossfit
#   - Gaming
#   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

darkmode: true

more_content: | # this will include new lines to allow paragraphs
  - Passed Java 11 OCA
  - Passed FCE exam
  - Multiple champion of the All-Russian Olympiads
  - Beta tester at JetBrains academy
  - Volunteer at summer computer schools
